config/routes.rb
Donator::Application.routes.draw do
  resources :artists
  resources :members
  get 'artists/:id/upvote' => 'artists#upvote'
  get 'faceoff' => 'artists#faceoff'
  get 'profile' => 'pages#profile'

  devise_for :users

  root 'pages#landing'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :upvotes
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
	belongs_to :user
	belongs_to :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_many :upvotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_action :set_artist, only: [:show, :edit, :update, :destroy]

	# GET /artists
	# GET /artists.json
	def index
		@artists = Artist.all
		@count = @artists.last.cycle
	end

	# GET /artists/1
	# GET /artists/1.json
	def show
	end

	# GET /artists/new
	def new
		@artist = Artist.new
	end

	def create
		@artist = Artist.new(artist_params)

		respond_to do |format|
			if @artist.save
				format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
				format.json { render action: 'show', status: :created, location: @artist }
			else
				format.html { render action: 'new' }
				format.json { render json: @artist.errors, status: :unprocessable_entity }
			end
		end
	end

	# GET /artists/1/edit
	def edit
	end

	def update
		respond_to do |format|
			if @artist.update(artist_params)
				format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @artist.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /artists/1
	# DELETE /artists/1.json
	def destroy
		@artist.destroy
		respond_to do |format|
			format.html { redirect_to artists_url }
			format.json { head :no_content }
		end
	end

	def upvote
		if signed_in?
			@artist = Artist.find(params[:id])
			@user = current_user
			if @artist.cycle != Artist.last.cycle
				flash[:alert] = "Sorry. You can only vote for artists in the current matchup."
				redirect_to '/faceoff'
			elsif @user.upvotes.count >0 && @user.upvotes.last.artist.cycle == @artist.cycle
				flash[:alert] = "You have already voted for this matchup."
				redirect_to '/faceoff'
			else
				@upvote = Upvote.create(
					:artist_id => @artist.id,
					:user_id => @user.id
					)
				flash[:notice] = "Successfully upvoted"
				redirect_to '/faceoff'
			end
		else
			flash[:alert] = "To vote, sign in."
			redirect_to new_user_session_path
		end
	end

	def faceoff
		@artists = Artist.all
		@count = @artists.last.cycle
		@lastartist = Artist.last
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_artist
			@artist = Artist.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def artist_params
			params.require(:artist).permit(:name, :label, :genre, :bio, :cycle, :track)
		end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	def create
		member = Stripe::Customer.create(
		  :card => params[:stripeToken],
		  :plan => "Standard",
		  :email => current_user.email
		)
		flash[:notice] = "Successfully suscribed!"
		redirect_to 'profile'
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def landing
		if signed_in?
			redirect_to '/faceoff'
		end
	end

	def profile
		@user = current_user
		@upvotes = @user.upvotes
		@artists = Artist.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
    <div class="field">
    <%= f.label :cycle %><br>
    <%= f.number_field :cycle %>
  </div>
  <div class="field">
    <%= f.label :track %><br>
    <%= f.text_field :track %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/faceoff.html.erb
<h1 style="text-align:center">Faceoff!</h1>
<div class="container">
	<div class="row">
		<% @artists.each do |artist| %>
			<% if artist.cycle == @count %>
				<% if artist == @lastartist %>
					<div class="col-sm-2">
						<div style="margin-top:150px">
							<h2 style="text-align:center">VS</h2>
						</div>
					</div>
				<% end %>
				<div class="col-sm-5">
					<h2 style="text-align:center"><%= artist.name%></h2>
					<p>
					  <strong>Label:</strong>
					  <%= artist.label %>
					</p>
					<p>
					  <strong>Genre:</strong>
					  <%= artist.genre %>
					</p>
					<p>
					  <strong>Bio:</strong>
					  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					</p>
					<p>
					  <strong>Upvotes:</strong>
					  <%= artist.upvotes.count %>
					</p>
					<p><iframe width="100%" height="166" scrolling="no" frameborder="no" src=<%="#{artist.track}"%>></iframe></p>
					<p style="text-align:center"><%= link_to 'Vote', "/artists/#{artist.id}/upvote", class:"btn btn-primary btn-lg"  %></p>
					</iframe>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/artists/index.html.erb
<% @count.times do |number| %>

	<h1>Cycle <%= @count - number%></h1>

	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Label</th>
				<th>Genre</th>
				<th>Bio</th>
				<th>Upvotes</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @artists.each do |artist| %>
				<% if artist.cycle == (@count - number) %>
					<tr>
						<td><%= artist.name %></td>
						<td><%= artist.label %></td>
						<td><%= artist.genre %></td>
						<td><%= artist.bio %></td>
						<td><%= artist.upvotes.count %></td>
						<td><%= link_to 'Show', artist %></td>
						<td><%= link_to 'Edit', edit_artist_path(artist) %></td>
						<td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>

	<br>

<% end %>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Label:</strong>
  <%= @artist.label %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @artist.genre %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @artist.bio %>
</p>

<p>
  <strong>Upvotes:</strong>
  <%= @artist.upvotes.count %>
</p>

  <strong>Cycle:</strong>
  <%= @artist.cycle %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="/">Bucks2Bands</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav navbar-left">
			<li><%= link_to 'Faceoff', '/faceoff' %></li>
			<li><%= link_to 'Previous Battles', artists_path %></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
	<% if signed_in? %>
		<li><%= link_to 'Profile', 'profile' %></li>
		<li><%= link_to 'Sign Out', destroy_user_session_path, :method=>:delete %></li>
	<% else %>
		<li><%= link_to 'Sign Up!', new_user_registration_path %></li>
		<li><%= link_to 'Sign In', new_user_session_path %></li>
	<% end %>
		</ul>
	</div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title>Donator</title>
	  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	  	<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% if notice %>
				<p class="alert alert-success" id="notice"><%= notice %></p>
			<%end%>
			<% if alert %>
			<div class="alert alert-danger"><%= alert %></div>
			<%end%>
		          	<%= yield %>
		</div>
	</body>
</html>

app/views/pages/landing.html.erb
<div class="jumbotron">
  <h1>Welcome</h1>
  <p>Bucks2Bands is a place for new bands to face-off for their fans' favor and earn some extra bucks for their tours and production.</p>
  <p><a class="btn btn-primary btn-lg" role="button" href='/users/sign_in'>Sign In</a> or check out <a href='/faceoff'>this week's faceoff</a>!</p>
</div>

app/views/pages/profile.html.erb
<div class="container">
	<h1>Profile</h1>
	<div class="row">
		<div class="col-sm-3">
			<h3>Personal Information</h3>
			<p><strong>Email:</strong><br>
			<%=@user.email%></p>
			<p><strong>Total Votes:</strong><br>
			<%=@user.upvotes.count%></p>
			<p><strong>Joined:</strong><br>
			<%=@user.created_at.strftime("%m/%d/%Y")%></p>
			<%= link_to 'Sign Out', destroy_user_session_path, :method=>:delete %>

	 		<%= form_tag members_path do%>
			  <script
			    src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
			    data-key="pk_test_3odwAUOok4nNSRCPjb7Y1h3U"
			    data-amount="2000"
			    data-name="Demo Site"
			    data-description="2 widgets ($20.00)"
			    data-image="/128x128.png">
			  </script>
			<%end%>

		</div>
		<div class="col-sm-9">
			<h3>Prior Upvotes</h3>
			<% @upvotes.each do |upvote| %>
				<h4>Cycle <%= upvote.artist.cycle %></h4>
				<table class="table">
					<thead>
						<tr>
							<th>Name</th>
							<th>Label</th>
							<th>Genre</th>
							<th>Bio</th>
							<th>Upvotes</th>
						</tr>
					</thead>
					<tbody>
						<% @artists.each do |artist| %>
							<% if artist.cycle == upvote.artist.cycle %>
								<% if artist != upvote.artist %>
									<tr style="color:#bbb">
								<% else %>
									<tr>
								<% end %>
										<td><%= artist.name %></td>
										<td><%= artist.label %></td>
										<td><%= artist.genre %></td>
										<td><%= artist.bio %></td>
										<td><%= artist.upvotes.count %></td>
									</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
			<% end %>
		</div>
	</div>
</div>